language: python
cache:
  directories:
    - ~/Library/Caches/pip

jobs:
  include:
  - stage: osx-test
    language: shell
    osx_image: xcode11.6 # Python 3.7.2, go 1.12.4
    os: osx
    before_install: skip
    script:  # no tests
      - go version
      - python3 --version
      - export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
      - make build_helm_binding && make build_helm_fetch_binding
      - python3 -m unittest tests.test_dependency_manager.DependencyManagerTest
      - python3 -m unittest tests.test_helm_input.HelmInputTest.test_compile_subcharts
      - python3 -m unittest tests.test_helm_input.HelmInputTest.test_compile_with_helm_params
      - python3 -m unittest tests.test_helm_input.HelmInputTest.test_compile_with_helm_values
      - python3 -m unittest tests.test_helm_input
    after_success: true  # overwrite after_success and do nothing
    after_deploy: skip
branches:
  only:
    - macos
install:
  - pip3 install -r requirements.txt